version: "2"
services:
  app:
    container_name: app
    command: npm run start
    restart: always
    build: .
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "8000:3000"
    volumes:
      - "${PWD}/src/:/app/src"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
